name: quranku_offline
description: "Al Quranku Offline."
publish_to: "none"
version: 1.1.4

environment:
  sdk: ^3.5.3

dependencies:
  audio_service: ^0.18.17
  audioplayers: ^6.3.0
  connectivity_plus: ^6.1.3
  device_info_plus: ^11.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^18.0.1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.3.1
  http: ^1.3.0
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.15
  logger: ^2.5.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  wakelock_plus: ^1.2.10
  workmanager: ^0.5.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/dzikir_pagi.json
    - assets/dzikir_petang.json
    - assets/dzikir_setelah_sholat.json
    - assets/surah/
    - assets/logo/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo-alquran-offline.png" # Path ke file ikon Anda
