name: quranku_offline
description: "Project Quranku Offline."
publish_to: "none"
version: 1.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/surah/
    - assets/logo/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo-alquran-offline.png" # Path ke file ikon Anda
